apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.service.name }}-{{ .Values.service.stage }}
  labels:
    app: {{ template "podtatohead.name" . }}
    chart: {{ template "podtatohead.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "podtatohead.name" . }}
      release: {{ .Release.Name }}
  strategy:
     canary:
    #blueGreen:
      # activeService: {{ template "podtatohead.fullname" . }}
      # previewService: {{ template "podtatohead.fullname" . }}-preview
       steps:
       - setWeight: 20
       - pause: {}
       - setWeight: 40
       - pause: {}
       - setWeight: 60
       - pause: {}
       - setWeight: 80
       - pause: {}      
  template:
    metadata:
      labels:
        app: {{ template "podtatohead.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 9000
          readinessProbe:
            httpGet:
              path: /
              port: 9000
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}


