apiVersion: v1
kind: Service
metadata:
  name: {{ template "podtatohead.fullname" . }}
  labels:
    app: {{ template "podtatohead.name" . }}
    chart: {{ template "podtatohead.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  type: ClusterIP    
  selector:
    app: {{ template "podtatohead.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "podtatohead.fullname" . }}-preview
  labels:
    app: {{ template "podtatohead.name" . }}
    chart: {{ template "podtatohead.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: {{ template "podtatohead.name" . }}
    release: {{ .Release.Name }}