apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "shipyard-delivery-podatohead"
spec:
  stages:
  - name: prod
    sequences:
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
    - name: delivery_canary_step1
      triggeredOn:
      - event: prod.delivery.finished
      tasks:  
      - name: release
      - name: test
        properties:
          teststrategy: canary_wait
          CanaryWaitDuration: 2m
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
    - name: delivery_canary_step2
      triggeredOn:
      - event: delivery_canary_step1
        selector:
          match:
            result: "pass"      
      tasks:  
      - name: release
      - name: test
        properties:
          teststrategy: canary_wait
          CanaryWaitDuration: 2m
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
    - name: rollback
      triggeredOn:
      - event: prod.delivery.finished
        selector:
          match:
            result: "fail"
      - event: prod.delivery_canary_step1.finished
        selector:
          match:
            result: "fail"
      - event: prod.delivery_canary_step2.finished
        selector:
          match:
            result: "fail"              
      tasks:
      - name: rollback