apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "shipyard-delivery-rollout"
spec:
  stages:
  - name: prod           # Initial Deployment, Test and Evaluation
    sequences:
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: approval
        properties:
          pass: manual
          warning: manual
  - name: canaryphase1  # Phase 1 of Rollout: Release, Test, Evaluate
    sequences:
    - name: delivery
      triggeredOn:
        - event: prod.delivery.finished
          selector:
            match:
              result: "pass"
      tasks:
      - name: release
      - name: test
        properties:
          teststrategy: real-user
          canarywaitduration: 2m
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
    - name: rollback
      triggeredOn:
      - event: canaryphase1.delivery.finished
        selector:
          match:
            result: "fail"
      tasks:
      - name: rollback          
  - name: canaryphase2   # Phase 2 of Rollout: Release, Test, Evaluate
    sequences:
    - name: delivery
      triggeredOn:
        - event: canaryphase1.delivery.finished
          selector:
            match:
              result: "pass"
      tasks:
      - name: release
      - name: test
        properties:
          teststrategy: real-user
          canarywaitduration: 2m
      - name: evaluation
      - name: approval
        properties:
          pass: automatic
          warning: automatic
    - name: rollback
      triggeredOn:
      - event: canaryphase2.delivery.finished
        selector:
          match:
            result: "fail"
      tasks:
      - name: rollback